export type VideoFieldType = 'text' | 'textarea' | 'number' | 'switch' | 'select' | 'url-list' | 'json';

export interface VideoFieldOption {
    label: string;
    value: string;
}

export interface VideoFieldDefinition {
    key: string;
    label: string;
    type: VideoFieldType;
    required?: boolean;
    placeholder?: string;
    description?: string;
    defaultValue?: string | number | boolean;
    options?: VideoFieldOption[];
    min?: number;
    max?: number;
    step?: number;
    rows?: number;
}

export interface VideoFamilyDefinition {
    id: string;
    label: string;
    description: string;
    createPath: string;
    queryPathTemplate?: string;
    supportNotes: string;
    fields: VideoFieldDefinition[];
}

export const VIDEO_FAMILIES: VideoFamilyDefinition[] = [
    {
        id: 'unified',
        label: '统一视频格式',
        description: '适合 Veo / Grok Video / 部分 Sora 聚合模型，统一走 /v1/video/create。',
        createPath: '/v1/video/create',
        queryPathTemplate: '/v1/video/query?id={taskId}',
        supportNotes: '支持模型通常出现在 /v1/models 的视频统一格式、openAI视频格式、grok视频条目里。',
        fields: [
            {
                key: 'model',
                label: '模型',
                type: 'select',
                required: true,
                options: [{ label: 'veo3.1-fast', value: 'veo3.1-fast' }],
                defaultValue: 'veo3.1-fast',
            },
            {
                key: 'prompt',
                label: '提示词',
                type: 'textarea',
                required: true,
                rows: 4,
                placeholder: '描述要生成的视频内容。',
            },
            {
                key: 'aspectRatio',
                label: '画幅比例',
                type: 'select',
                options: [
                    { label: '16:9', value: '16:9' },
                    { label: '9:16', value: '9:16' },
                    { label: '1:1', value: '1:1' },
                    { label: '3:2', value: '3:2' },
                    { label: '2:3', value: '2:3' },
                ],
                defaultValue: '16:9',
            },
            {
                key: 'size',
                label: '清晰度',
                type: 'select',
                options: [
                    { label: '自动', value: '' },
                    { label: '720P', value: '720P' },
                    { label: '1080P', value: '1080P' },
                ],
                defaultValue: '',
            },
            {
                key: 'imageUrls',
                label: '参考图 URL',
                type: 'url-list',
                placeholder: '每行一个 URL，可空。',
                description: '统一格式支持图生视频或多图参考。',
            },
            {
                key: 'enhancePrompt',
                label: '增强提示词',
                type: 'switch',
                defaultValue: true,
            },
            {
                key: 'enableUpsample',
                label: '开启增强采样',
                type: 'switch',
                defaultValue: false,
            },
        ],
    },
    {
        id: 'openai-official',
        label: 'OpenAI 官方视频格式',
        description: '适合 Sora / Veo 官方风格接口，走 /v1/videos。',
        createPath: '/v1/videos',
        queryPathTemplate: '/v1/videos/{taskId}',
        supportNotes: '当前 key 若支持 openAI官方视频格式，对应模型通常会出现在 /v1/models。',
        fields: [
            {
                key: 'model',
                label: '模型',
                type: 'select',
                required: true,
                options: [{ label: 'sora-2', value: 'sora-2' }],
                defaultValue: 'sora-2',
            },
            {
                key: 'prompt',
                label: '提示词',
                type: 'textarea',
                required: true,
                rows: 4,
            },
            {
                key: 'seconds',
                label: '时长(秒)',
                type: 'number',
                required: true,
                min: 1,
                max: 20,
                step: 1,
                defaultValue: 5,
            },
            {
                key: 'size',
                label: '尺寸',
                type: 'select',
                options: [
                    { label: '16x9', value: '16x9' },
                    { label: '9x16', value: '9x16' },
                    { label: '1x1', value: '1x1' },
                ],
                defaultValue: '16x9',
            },
            {
                key: 'watermark',
                label: '带水印',
                type: 'switch',
                defaultValue: false,
            },
            {
                key: 'referenceImageUrl',
                label: '参考图 URL',
                type: 'text',
                placeholder: '官方格式会把这张图下载后作为 input_reference 上传。',
            },
        ],
    },
    {
        id: 'hailuo',
        label: '海螺视频',
        description: 'MiniMax Hailuo 系列，走 /minimax/v1/video_generation。',
        createPath: '/minimax/v1/video_generation',
        queryPathTemplate: '/minimax/v1/query/video_generation?task_id={taskId}',
        supportNotes: '当前 key 支持 MiniMax-Hailuo-02 / MiniMax-Hailuo-2.3。',
        fields: [
            {
                key: 'model',
                label: '模型',
                type: 'select',
                required: true,
                options: [{ label: 'MiniMax-Hailuo-02', value: 'MiniMax-Hailuo-02' }],
                defaultValue: 'MiniMax-Hailuo-02',
            },
            {
                key: 'prompt',
                label: '提示词',
                type: 'textarea',
                required: true,
                rows: 4,
            },
            {
                key: 'duration',
                label: '时长(秒)',
                type: 'number',
                min: 1,
                max: 10,
                step: 1,
                defaultValue: 6,
            },
            {
                key: 'firstFrameImage',
                label: '首帧图片 URL',
                type: 'text',
                placeholder: '可空，用于图生视频。',
            },
            {
                key: 'lastFrameImage',
                label: '尾帧图片 URL',
                type: 'text',
                placeholder: '可空，用于首尾帧控制。',
            },
        ],
    },
    {
        id: 'runway-image',
        label: 'Runway 图生视频',
        description: 'Runway Gen3 / Gen4 Turbo，走 /runwayml/v1/image_to_video。',
        createPath: '/runwayml/v1/image_to_video',
        queryPathTemplate: '/runwayml/v1/tasks/{taskId}',
        supportNotes: '当前 key 支持 runwayml-gen3a_turbo-* 与 runwayml-gen4_turbo-*。',
        fields: [
            {
                key: 'model',
                label: '模型',
                type: 'select',
                required: true,
                options: [{ label: 'gen4_turbo', value: 'gen4_turbo' }],
                defaultValue: 'gen4_turbo',
            },
            {
                key: 'promptImage',
                label: '首帧图 URL',
                type: 'text',
                required: true,
            },
            {
                key: 'promptText',
                label: '动作提示词',
                type: 'textarea',
                required: true,
                rows: 3,
            },
            {
                key: 'duration',
                label: '时长(秒)',
                type: 'number',
                min: 1,
                max: 10,
                step: 1,
                defaultValue: 5,
            },
            {
                key: 'ratio',
                label: '输出尺寸',
                type: 'select',
                options: [
                    { label: '1280:768', value: '1280:768' },
                    { label: '768:1280', value: '768:1280' },
                    { label: '1024:1024', value: '1024:1024' },
                ],
                defaultValue: '1280:768',
            },
            {
                key: 'watermark',
                label: '带水印',
                type: 'switch',
                defaultValue: false,
            },
        ],
    },
    {
        id: 'kling-text',
        label: 'Kling 文生视频',
        description: '可灵官方接口文生视频，走 /kling/v1/videos/text2video。',
        createPath: '/kling/v1/videos/text2video',
        queryPathTemplate: '/kling/v1/videos/text2video/{taskId}',
        supportNotes: '当前 key 的 /v1/models 返回的是 kling-video 泛型权限，提交时会映射到模型名称字段。',
        fields: [
            {
                key: 'modelName',
                label: '模型名称',
                type: 'select',
                required: true,
                options: [{ label: 'kling-v1', value: 'kling-v1' }],
                defaultValue: 'kling-v1',
            },
            {
                key: 'prompt',
                label: '提示词',
                type: 'textarea',
                required: true,
                rows: 4,
            },
            {
                key: 'negativePrompt',
                label: '负面提示词',
                type: 'text',
            },
            {
                key: 'cfgScale',
                label: '提示词权重',
                type: 'number',
                min: 0,
                max: 1,
                step: 0.1,
                defaultValue: 0.5,
            },
            {
                key: 'mode',
                label: '生成模式',
                type: 'select',
                options: [
                    { label: '标准 (std)', value: 'std' },
                    { label: '高质 (pro)', value: 'pro' },
                ],
                defaultValue: 'std',
            },
            {
                key: 'sound',
                label: '声音开关',
                type: 'select',
                options: [
                    { label: '关闭 (off)', value: 'off' },
                    { label: '开启 (on)', value: 'on' },
                ],
                defaultValue: 'off',
            },
            {
                key: 'aspectRatio',
                label: '画幅比例',
                type: 'select',
                options: [
                    { label: '16:9', value: '16:9' },
                    { label: '9:16', value: '9:16' },
                    { label: '1:1', value: '1:1' },
                ],
                defaultValue: '16:9',
            },
            {
                key: 'duration',
                label: '时长(秒)',
                type: 'select',
                options: [
                    { label: '5', value: '5' },
                    { label: '10', value: '10' },
                ],
                defaultValue: '5',
            },
            {
                key: 'cameraControlJson',
                label: '运镜控制(JSON)',
                type: 'json',
                rows: 5,
                placeholder: '{"type":"simple","config":{"horizontal":1}}',
            },
            {
                key: 'callbackUrl',
                label: '回调地址 URL',
                type: 'text',
            },
            {
                key: 'externalTaskId',
                label: '外部任务 ID',
                type: 'text',
            },
        ],
    },
    {
        id: 'kling-image',
        label: 'Kling 图生视频',
        description: '可灵官方接口图生视频，走 /kling/v1/videos/image2video。',
        createPath: '/kling/v1/videos/image2video',
        queryPathTemplate: '/kling/v1/videos/image2video/{taskId}',
        supportNotes: '支持起始图、尾帧图、遮罩等图生视频参数。',
        fields: [
            {
                key: 'modelName',
                label: '模型名称',
                type: 'select',
                required: true,
                options: [{ label: 'kling-v1', value: 'kling-v1' }],
                defaultValue: 'kling-v1',
            },
            {
                key: 'image',
                label: '起始图 URL',
                type: 'text',
                required: true,
            },
            {
                key: 'imageTail',
                label: '尾帧图 URL',
                type: 'text',
            },
            {
                key: 'prompt',
                label: '提示词',
                type: 'textarea',
                rows: 3,
            },
            {
                key: 'negativePrompt',
                label: '负面提示词',
                type: 'text',
            },
            {
                key: 'cfgScale',
                label: '提示词权重',
                type: 'number',
                min: 0,
                max: 1,
                step: 0.1,
                defaultValue: 0.5,
            },
            {
                key: 'mode',
                label: '生成模式',
                type: 'select',
                options: [
                    { label: '标准 (std)', value: 'std' },
                    { label: '高质 (pro)', value: 'pro' },
                ],
                defaultValue: 'std',
            },
            {
                key: 'duration',
                label: '时长(秒)',
                type: 'select',
                options: [
                    { label: '5', value: '5' },
                    { label: '10', value: '10' },
                ],
                defaultValue: '5',
            },
            {
                key: 'staticMask',
                label: '静态遮罩 URL',
                type: 'text',
            },
            {
                key: 'dynamicMasksJson',
                label: '动态遮罩(JSON)',
                type: 'json',
                rows: 5,
            },
        ],
    },
    {
        id: 'vidu-text',
        label: 'VIDU 文生视频',
        description: 'VIDU 官方文生视频，走 /ent/v2/text2video。',
        createPath: '/ent/v2/text2video',
        queryPathTemplate: '/ent/v2/tasks/{taskId}/creations',
        supportNotes: '当前 key 支持 viduq1 / viduq2 / viduq3-pro 等 VIDU 系模型。',
        fields: [
            {
                key: 'model',
                label: '模型',
                type: 'select',
                required: true,
                options: [{ label: 'viduq2', value: 'viduq2' }],
                defaultValue: 'viduq2',
            },
            {
                key: 'prompt',
                label: '提示词',
                type: 'textarea',
                required: true,
                rows: 4,
            },
            {
                key: 'duration',
                label: '时长(秒)',
                type: 'number',
                min: 2,
                max: 8,
                step: 1,
                defaultValue: 5,
            },
            {
                key: 'resolution',
                label: '分辨率',
                type: 'select',
                options: [
                    { label: '720p', value: '720p' },
                    { label: '1080p', value: '1080p' },
                ],
                defaultValue: '720p',
            },
            {
                key: 'aspectRatio',
                label: '画幅比例',
                type: 'select',
                options: [
                    { label: '16:9', value: '16:9' },
                    { label: '9:16', value: '9:16' },
                    { label: '1:1', value: '1:1' },
                ],
                defaultValue: '16:9',
            },
            {
                key: 'movementAmplitude',
                label: '运动幅度',
                type: 'select',
                options: [
                    { label: '自动 (auto)', value: 'auto' },
                    { label: '标准 (standard)', value: 'standard' },
                    { label: '大幅 (large)', value: 'large' },
                ],
                defaultValue: 'auto',
            },
            {
                key: 'audio',
                label: '生成音频',
                type: 'switch',
                defaultValue: false,
            },
            {
                key: 'bgm',
                label: '背景音乐',
                type: 'switch',
                defaultValue: false,
            },
            {
                key: 'watermark',
                label: '添加水印',
                type: 'switch',
                defaultValue: false,
            },
            {
                key: 'offPeak',
                label: '错峰模式',
                type: 'switch',
                defaultValue: false,
            },
            {
                key: 'payload',
                label: '透传参数',
                type: 'text',
            },
            {
                key: 'clientRequestId',
                label: '客户端请求 ID',
                type: 'text',
            },
        ],
    },
    {
        id: 'vidu-image',
        label: 'VIDU 图生视频',
        description: 'VIDU 图生视频，走 /ent/v2/img2video。',
        createPath: '/ent/v2/img2video',
        queryPathTemplate: '/ent/v2/tasks/{taskId}/creations',
        supportNotes: '适合 viduq1-classic / viduq2-turbo / viduq3-pro 等图生视频模型。',
        fields: [
            {
                key: 'model',
                label: '模型',
                type: 'select',
                required: true,
                options: [{ label: 'viduq2-turbo', value: 'viduq2-turbo' }],
                defaultValue: 'viduq2-turbo',
            },
            {
                key: 'imageUrls',
                label: '图片 URL',
                type: 'url-list',
                required: true,
                placeholder: '至少一行 URL。',
            },
            {
                key: 'prompt',
                label: '提示词',
                type: 'textarea',
                rows: 3,
            },
            {
                key: 'duration',
                label: '时长(秒)',
                type: 'number',
                min: 2,
                max: 8,
                step: 1,
                defaultValue: 2,
            },
            {
                key: 'resolution',
                label: '分辨率',
                type: 'select',
                options: [
                    { label: '720p', value: '720p' },
                    { label: '1080p', value: '1080p' },
                ],
                defaultValue: '720p',
            },
            {
                key: 'aspectRatio',
                label: '画幅比例',
                type: 'select',
                options: [
                    { label: '16:9', value: '16:9' },
                    { label: '9:16', value: '9:16' },
                    { label: '1:1', value: '1:1' },
                ],
                defaultValue: '16:9',
            },
            {
                key: 'movementAmplitude',
                label: '运动幅度',
                type: 'select',
                options: [
                    { label: '自动 (auto)', value: 'auto' },
                    { label: '标准 (standard)', value: 'standard' },
                    { label: '大幅 (large)', value: 'large' },
                ],
                defaultValue: 'standard',
            },
            {
                key: 'audio',
                label: '生成音频',
                type: 'switch',
                defaultValue: false,
            },
            {
                key: 'bgm',
                label: '背景音乐',
                type: 'switch',
                defaultValue: false,
            },
            {
                key: 'watermark',
                label: '添加水印',
                type: 'switch',
                defaultValue: false,
            },
            {
                key: 'offPeak',
                label: '错峰模式',
                type: 'switch',
                defaultValue: false,
            },
        ],
    },
    {
        id: 'vidu-reference',
        label: 'VIDU 参考主体生视频',
        description: 'VIDU 参考主体视频，走 /ent/v2/reference2video。',
        createPath: '/ent/v2/reference2video',
        queryPathTemplate: '/ent/v2/tasks/{taskId}/creations',
        supportNotes: '参考主体结构较复杂，页面提供单独的 JSON 参数入口。',
        fields: [
            {
                key: 'model',
                label: '模型',
                type: 'select',
                required: true,
                options: [{ label: 'viduq2', value: 'viduq2' }],
                defaultValue: 'viduq2',
            },
            {
                key: 'prompt',
                label: '提示词',
                type: 'textarea',
                required: true,
                rows: 4,
            },
            {
                key: 'subjectsJson',
                label: '参考主体(JSON)',
                type: 'json',
                required: true,
                rows: 6,
                placeholder: '[{"id":"cat","images":["https://..."]}]',
            },
            {
                key: 'duration',
                label: '时长(秒)',
                type: 'number',
                min: 2,
                max: 8,
                step: 1,
                defaultValue: 5,
            },
            {
                key: 'resolution',
                label: '分辨率',
                type: 'select',
                options: [
                    { label: '720p', value: '720p' },
                    { label: '1080p', value: '1080p' },
                ],
                defaultValue: '720p',
            },
            {
                key: 'aspectRatio',
                label: '画幅比例',
                type: 'select',
                options: [
                    { label: '16:9', value: '16:9' },
                    { label: '9:16', value: '9:16' },
                    { label: '1:1', value: '1:1' },
                ],
                defaultValue: '16:9',
            },
            {
                key: 'movementAmplitude',
                label: '运动幅度',
                type: 'select',
                options: [
                    { label: '自动 (auto)', value: 'auto' },
                    { label: '标准 (standard)', value: 'standard' },
                    { label: '大幅 (large)', value: 'large' },
                ],
                defaultValue: 'auto',
            },
        ],
    },
    {
        id: 'vidu-start-end',
        label: 'VIDU 首尾帧视频',
        description: 'VIDU 首尾帧控制视频，走 /ent/v2/start-end2video。',
        createPath: '/ent/v2/start-end2video',
        queryPathTemplate: '/ent/v2/tasks/{taskId}/creations',
        supportNotes: '需要传入两张图片 URL，按开始帧 / 结束帧顺序填写。',
        fields: [
            {
                key: 'model',
                label: '模型',
                type: 'select',
                required: true,
                options: [{ label: 'viduq2-turbo', value: 'viduq2-turbo' }],
                defaultValue: 'viduq2-turbo',
            },
            {
                key: 'imageUrls',
                label: '首尾帧 URL',
                type: 'url-list',
                required: true,
                placeholder: '第一行首帧，第二行尾帧。',
            },
            {
                key: 'prompt',
                label: '提示词',
                type: 'textarea',
                rows: 3,
            },
            {
                key: 'duration',
                label: '时长(秒)',
                type: 'number',
                min: 2,
                max: 8,
                step: 1,
                defaultValue: 5,
            },
            {
                key: 'resolution',
                label: '分辨率',
                type: 'select',
                options: [
                    { label: '720p', value: '720p' },
                    { label: '1080p', value: '1080p' },
                ],
                defaultValue: '720p',
            },
            {
                key: 'movementAmplitude',
                label: '运动幅度',
                type: 'select',
                options: [
                    { label: '自动 (auto)', value: 'auto' },
                    { label: '标准 (standard)', value: 'standard' },
                    { label: '大幅 (large)', value: 'large' },
                ],
                defaultValue: 'auto',
            },
        ],
    },
    {
        id: 'wan-image',
        label: '通义万象视频',
        description: '阿里通义万象视频，走 /alibailian/api/v1/services/aigc/video-generation/video-synthesis。',
        createPath: '/alibailian/api/v1/services/aigc/video-generation/video-synthesis',
        queryPathTemplate: '/alibailian/api/v1/tasks/{taskId}',
        supportNotes: '当前 key 支持 wan2.5-i2v-preview / wan2.6-i2v / wan2.6-i2v-flash。',
        fields: [
            {
                key: 'model',
                label: '模型',
                type: 'select',
                required: true,
                options: [{ label: 'wan2.6-i2v-flash', value: 'wan2.6-i2v-flash' }],
                defaultValue: 'wan2.6-i2v-flash',
            },
            {
                key: 'prompt',
                label: '提示词',
                type: 'textarea',
                required: true,
                rows: 4,
            },
            {
                key: 'imageUrl',
                label: '参考图 URL',
                type: 'text',
                required: true,
            },
            {
                key: 'resolution',
                label: '分辨率',
                type: 'select',
                options: [
                    { label: '480P', value: '480P' },
                    { label: '720P', value: '720P' },
                ],
                defaultValue: '720P',
            },
            {
                key: 'promptExtend',
                label: '扩写提示词',
                type: 'switch',
                defaultValue: true,
            },
            {
                key: 'audio',
                label: '生成音频',
                type: 'switch',
                defaultValue: false,
            },
            {
                key: 'duration',
                label: '时长(秒)',
                type: 'number',
                min: 1,
                max: 10,
                step: 1,
            },
        ],
    },
    {
        id: 'tencent-aigc',
        label: '腾讯 AIGC 视频',
        description: '腾讯云视频生成接口，走 /tencent-vod/v1/aigc-video。',
        createPath: '/tencent-vod/v1/aigc-video',
        queryPathTemplate: '/tencent-vod/v1/query/{taskId}',
        supportNotes: '当前 token 不一定开通腾讯视频能力，但参数已全部配好，可直接切换测试。',
        fields: [
            {
                key: 'modelName',
                label: '模型名称',
                type: 'select',
                required: true,
                options: [{ label: 'Kling', value: 'Kling' }],
                defaultValue: 'Kling',
            },
            {
                key: 'modelVersion',
                label: '模型版本',
                type: 'text',
                required: true,
                defaultValue: '1.6',
            },
            {
                key: 'prompt',
                label: '提示词',
                type: 'textarea',
                required: true,
                rows: 4,
            },
            {
                key: 'negativePrompt',
                label: '负面提示词',
                type: 'text',
            },
            {
                key: 'enhancePromptMode',
                label: '提示词增强',
                type: 'select',
                options: [
                    { label: '开启 (Enabled)', value: 'Enabled' },
                    { label: '关闭 (Disabled)', value: 'Disabled' },
                ],
                defaultValue: 'Enabled',
            },
            {
                key: 'storageMode',
                label: '存储模式',
                type: 'select',
                options: [
                    { label: '临时存储 (Temporary)', value: 'Temporary' },
                    { label: '持久存储 (Persistent)', value: 'Persistent' },
                ],
                defaultValue: 'Temporary',
            },
            {
                key: 'mediaName',
                label: '媒体名称',
                type: 'text',
                defaultValue: 'video-generator',
            },
            {
                key: 'duration',
                label: '时长(秒)',
                type: 'number',
                min: 1,
                max: 10,
                step: 1,
                defaultValue: 5,
            },
            {
                key: 'resolution',
                label: '分辨率',
                type: 'select',
                options: [
                    { label: '720P', value: '720P' },
                    { label: '1080P', value: '1080P' },
                ],
                defaultValue: '720P',
            },
            {
                key: 'aspectRatio',
                label: '画幅比例',
                type: 'select',
                options: [
                    { label: '16:9', value: '16:9' },
                    { label: '9:16', value: '9:16' },
                    { label: '1:1', value: '1:1' },
                ],
                defaultValue: '16:9',
            },
            {
                key: 'audioGeneration',
                label: '音频生成',
                type: 'select',
                options: [
                    { label: '开启 (Enabled)', value: 'Enabled' },
                    { label: '关闭 (Disabled)', value: 'Disabled' },
                ],
                defaultValue: 'Disabled',
            },
            {
                key: 'personGeneration',
                label: '人物生成',
                type: 'select',
                options: [
                    { label: '允许成人 (AllowAdult)', value: 'AllowAdult' },
                    { label: '禁止成人 (DoNotAllow)', value: 'DoNotAllow' },
                ],
                defaultValue: 'AllowAdult',
            },
            {
                key: 'inputComplianceCheck',
                label: '输入合规检查',
                type: 'select',
                options: [
                    { label: '开启 (Enabled)', value: 'Enabled' },
                    { label: '关闭 (Disabled)', value: 'Disabled' },
                ],
                defaultValue: 'Enabled',
            },
            {
                key: 'outputComplianceCheck',
                label: '输出合规检查',
                type: 'select',
                options: [
                    { label: '开启 (Enabled)', value: 'Enabled' },
                    { label: '关闭 (Disabled)', value: 'Disabled' },
                ],
                defaultValue: 'Enabled',
            },
            {
                key: 'enhanceSwitch',
                label: '增强开关',
                type: 'select',
                options: [
                    { label: '开启 (Enabled)', value: 'Enabled' },
                    { label: '关闭 (Disabled)', value: 'Disabled' },
                ],
                defaultValue: 'Enabled',
            },
        ],
    },
];
